//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFINANCE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iFINANCEModel : DbContext
    {
        public iFINANCEModel()
            : base("name=iFINANCEModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCategory> AccountCategories { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MasterAccount> MasterAccounts { get; set; }
        public virtual DbSet<NonAdminUser> NonAdminUsers { get; set; }
        public virtual DbSet<TransactionLine> TransactionLines { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserPassword> UserPasswords { get; set; }
    }
}
